name: CI Stage Load Test

on:
  workflow_dispatch:
    inputs:
      concurrency:
        type: string
        description: Number of concurrent user journey threads
      journey_repeats:
        type: string
        description: Number of sequential user journey repetitions

jobs:
  load_test:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_DIR: ${{ github.workspace }}/tests/load-test/.artifacts

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Prepare Load Test
      working-directory: ./tests/load-tests
      env:
        STAGING_USERS_1: ${{ secrets.STAGING_USERS_1 }}
        STAGING_USERS_2: ${{ secrets.STAGING_USERS_2 }}
        STAGING_USERS_3: ${{ secrets.STAGING_USERS_3 }}
        STAGING_USERS_4: ${{ secrets.STAGING_USERS_4 }}
      run: ./ci-scripts/merge-json.sh $STAGING_USERS_1 $STAGING_USERS_2 $STAGING_USERS_3 $STAGING_USERS_4

    - name: Run Load Test
      working-directory: ./tests/load-tests
      env:
        CONCURRENCY: ${{ github.event.inputs.concurrency }}
        JOURNEY_REPEATS: ${{ github.event.inputs.journey_repeats }}
      run: |
        ./run-stage.sh

    - name: Collect results
      working-directory: ./tests/load-tests
      env:
        CONCURRENCY: ${{ github.event.inputs.concurrency }}
        STAGE_MEMBER_CLUSTER: ${{ secrets.STAGE_MEMBER_CLUSTER }}
        OCP_PROMETHEUS_TOKEN: ${{ secrets.OCP_PROMETHEUS_TOKEN }}
      run: |
        ./ci-scripts/stage/collect-results.sh . $CONCURRENCY

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rhtap-load-test-stage
        path: |
          ${{ env.ARTIFACT_DIR }}
